// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package go_micro_srv_GetImageCd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Response struct {
	Errno                string          `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string          `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	Pix                  []byte          `protobuf:"bytes,3,opt,name=Pix,proto3" json:"Pix,omitempty"`
	Stride               int64           `protobuf:"varint,4,opt,name=Stride,proto3" json:"Stride,omitempty"`
	Min                  *Response_Point `protobuf:"bytes,5,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  *Response_Point `protobuf:"bytes,6,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetPix() []byte {
	if m != nil {
		return m.Pix
	}
	return nil
}

func (m *Response) GetStride() int64 {
	if m != nil {
		return m.Stride
	}
	return 0
}

func (m *Response) GetMin() *Response_Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *Response) GetMax() *Response_Point {
	if m != nil {
		return m.Max
	}
	return nil
}

type Response_Point struct {
	X                    int64    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Point) Reset()         { *m = Response_Point{} }
func (m *Response_Point) String() string { return proto.CompactTextString(m) }
func (*Response_Point) ProtoMessage()    {}
func (*Response_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2, 0}
}

func (m *Response_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Point.Unmarshal(m, b)
}
func (m *Response_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Point.Marshal(b, m, deterministic)
}
func (m *Response_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Point.Merge(m, src)
}
func (m *Response_Point) XXX_Size() int {
	return xxx_messageInfo_Response_Point.Size(m)
}
func (m *Response_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Point proto.InternalMessageInfo

func (m *Response_Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Response_Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.GetImageCd.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetImageCd.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetImageCd.Response")
	proto.RegisterType((*Response_Point)(nil), "go.micro.srv.GetImageCd.Response.Point")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x8d, 0x59, 0x5b, 0x7d, 0x4e, 0x90, 0x20, 0x1a, 0x26, 0x42, 0xad, 0x07, 0x7b, 0xca,
	0x61, 0x9e, 0x3c, 0x4b, 0x11, 0x0f, 0x83, 0x91, 0x5d, 0xb6, 0x8b, 0x10, 0xed, 0xa3, 0x04, 0x6c,
	0x53, 0x93, 0x56, 0xea, 0x1f, 0x2f, 0x48, 0xb2, 0x8a, 0x27, 0x95, 0xdd, 0xbe, 0x5f, 0xf2, 0xbe,
	0xbc, 0xf7, 0xbd, 0xc0, 0x31, 0x0e, 0xaa, 0x6e, 0x5f, 0x51, 0xb4, 0xd6, 0x74, 0x86, 0x9d, 0x57,
	0x46, 0xd4, 0xfa, 0xc5, 0x1a, 0xe1, 0xec, 0xbb, 0x78, 0xc0, 0xee, 0xb1, 0x56, 0x15, 0xde, 0x97,
	0xd9, 0x05, 0x24, 0x0b, 0x74, 0x4e, 0x55, 0xc8, 0x4e, 0x80, 0x3a, 0xf5, 0xc1, 0x49, 0x4a, 0xf2,
	0x43, 0xe9, 0x65, 0x76, 0x09, 0x89, 0xc4, 0xb7, 0x1e, 0x5d, 0xc7, 0x18, 0x4c, 0xfa, 0x5e, 0x97,
	0xe3, 0x6d, 0xd0, 0xd9, 0x27, 0x81, 0x03, 0x89, 0xae, 0x35, 0x8d, 0x43, 0x76, 0x0a, 0x51, 0x61,
	0x6d, 0x63, 0xc6, 0x8a, 0x2d, 0xb0, 0x33, 0x88, 0x0b, 0x6b, 0x6b, 0x57, 0xf1, 0xfd, 0x70, 0x3c,
	0x92, 0xef, 0xb5, 0xd4, 0x03, 0xa7, 0x29, 0xc9, 0xa7, 0xd2, 0x4b, 0x5f, 0xb9, 0xea, 0xac, 0x2e,
	0x91, 0x4f, 0x52, 0x92, 0x53, 0x39, 0x12, 0xbb, 0x03, 0xba, 0xd0, 0x0d, 0x8f, 0x52, 0x92, 0x1f,
	0xcd, 0x6f, 0xc4, 0x2f, 0x39, 0xc4, 0xf7, 0x1c, 0x62, 0x69, 0x74, 0xd3, 0x49, 0xef, 0x09, 0x56,
	0x35, 0xf0, 0x78, 0x57, 0xab, 0x1a, 0x66, 0xd7, 0x10, 0x05, 0x62, 0x53, 0x20, 0xeb, 0x10, 0x89,
	0x4a, 0xb2, 0xf6, 0xb4, 0x09, 0x49, 0xa8, 0x24, 0x9b, 0xf9, 0x13, 0x24, 0xc5, 0x76, 0xcb, 0x6c,
	0x05, 0xf0, 0xf3, 0x22, 0x4b, 0xff, 0xe8, 0x15, 0xd6, 0x39, 0xbb, 0xfa, 0x77, 0x9a, 0x6c, 0xef,
	0x39, 0x0e, 0x7f, 0x77, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x74, 0xf8, 0xe4, 0xcc, 0x01,
	0x00, 0x00,
}
