// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package go_micro_srv_GetUserAuth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Sessionid            string   `protobuf:"bytes,1,opt,name=Sessionid,proto3" json:"Sessionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionid() string {
	if m != nil {
		return m.Sessionid
	}
	return ""
}

type Response struct {
	Errno                string   `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	RealName             string   `protobuf:"bytes,3,opt,name=Real_name,json=RealName,proto3" json:"Real_name,omitempty"`
	IdCard               string   `protobuf:"bytes,4,opt,name=Id_card,json=IdCard,proto3" json:"Id_card,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *Response) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.GetUserAuth.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetUserAuth.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetUserAuth.Response")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xad, 0xd5, 0xa6, 0x19, 0x11, 0x64, 0x10, 0x5d, 0xac, 0x07, 0xdd, 0x8b, 0x9e, 0xf6,
	0xa0, 0x4f, 0x20, 0x12, 0xa4, 0x07, 0x3d, 0x44, 0xf4, 0x5a, 0xc6, 0xee, 0x10, 0x03, 0xdd, 0xdd,
	0x38, 0x93, 0x8a, 0xbe, 0xbd, 0x34, 0x09, 0xe8, 0xc5, 0xde, 0xe6, 0xff, 0xe7, 0x9b, 0xc3, 0x37,
	0x70, 0xc8, 0x5f, 0x14, 0x9a, 0x15, 0xbb, 0x46, 0x52, 0x9b, 0xd0, 0x54, 0xc9, 0x85, 0x7a, 0x29,
	0xc9, 0xa9, 0x7c, 0xba, 0x07, 0x6e, 0x5f, 0x94, 0xe5, 0x6e, 0xdd, 0xbe, 0xdb, 0x19, 0x64, 0x8f,
	0xac, 0x4a, 0x15, 0xe3, 0x11, 0x8c, 0x95, 0xbe, 0xcd, 0xe8, 0x62, 0x74, 0x9d, 0x97, 0x9b, 0xd1,
	0x5e, 0x41, 0x56, 0xf2, 0xc7, 0x9a, 0xb5, 0xc5, 0x73, 0xc8, 0x9f, 0x59, 0xb5, 0x4e, 0xb1, 0xf6,
	0x03, 0xf2, 0x5b, 0xd8, 0x08, 0xd3, 0x92, 0xb5, 0x49, 0x51, 0x19, 0x8f, 0x61, 0xbf, 0x10, 0x89,
	0x69, 0xa0, 0xfa, 0x80, 0x27, 0x30, 0x29, 0x44, 0x82, 0x56, 0x66, 0xb7, 0xab, 0x87, 0x84, 0x33,
	0xc8, 0x4b, 0xa6, 0xd5, 0x22, 0x52, 0x60, 0x33, 0xee, 0x56, 0xd3, 0x4d, 0xf1, 0x44, 0x81, 0xf1,
	0x14, 0xb2, 0xb9, 0x5f, 0x2c, 0x49, 0xbc, 0xd9, 0xeb, 0xaf, 0xe6, 0xfe, 0x9e, 0xc4, 0xdf, 0x10,
	0x64, 0x45, 0x2f, 0x88, 0xaf, 0x70, 0xf0, 0xc7, 0x07, 0x2f, 0xdd, 0x7f, 0xaa, 0x6e, 0x50, 0x39,
	0xb3, 0xdb, 0x90, 0x5e, 0xc2, 0xee, 0xbc, 0x4d, 0xba, 0xcf, 0xdd, 0xfe, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x92, 0xee, 0x59, 0x99, 0x4a, 0x01, 0x00, 0x00,
}
